---
# handlers file for ansible-role-reverse-proxy
          - name: Créer un lien
            file:
                    src: /etc/nginx/sites-available/reverse-proxy.conf
                    dest: /etc/nginx/sites-enabled/reverse-proxy.conf
                    state: link

          - name: Unlink default
            shell: unlink /etc/nginx/sites-enabled/default
